name: Request YouTube Data (Chopstick View v2)

# 一時的な実行方法
on:
  schedule:
    - cron: '* */1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
# おまじない
      - uses: actions/checkout@v2

# Pythonのセットアップ
      - name: Setup python
        uses: actions/setup-python@v2 
        with:
          python-version: "3.8"

# 必要なパッケージのインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade google-api-python-client
          pip install -r requirements.txt

# チャットを取得するファイルを実行させる
      - name: Run settings.py & chopstick-view.py
        run: |
          python settings.py
          python chopstick-view-v2.py
        env:
          YT_API: ${{ secrets.YT_API_ENV_V2 }}

# Gitのセットアップ
      - name: Setup Git
        run: |
          git config --local user.name "Murayu0225"
          git config --local user.email "murayu@assistant-app.com"

# ライブチャットデータを保存
      - name: Commit and Push
        run: |
          git config pull.rebase false
          git add .
          git commit -m "Chopstick data was Downloaded!" || echo "No changes to commit."
          git pull origin main
          git push origin main
