name: Request Live Chat Data

# 一時的な実行方法
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2 
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run settings.py
        env:
          YT_API: ${{ secrets.YT_API_ENV }}
          YT_URL: ${{ secrets.YT_URL_ENV }}
        run: |
          python settings.py

# チャットを取得するファイルを実行させる
      - name: Run main.py
        # env:
          # YT_URL: '${{ secrets.YT_URL_ENV }}'
        run: |
          python main.py

# ライブチャットデータを保存
      - name: Commit and Push
        run: |
          git config user.name "Murayu0225"
          git config user.email "murayu@assistant-app.com"
          git add .
          git commit -m "Downloaded!" || echo "No changes to commit"
          git pull  origin main
          git push origin main
