name: Request Live Chat Data

# 一時的な実行方法
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
# おまじない
      - uses: actions/checkout@v2

# Pythonのセットアップ
      - name: Setup python
        uses: actions/setup-python@v2 
        with:
          python-version: "3.8"

# 必要なパッケージのインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

# チャットを取得するファイルを実行させる
      - name: Run settings.py & main.py
        run: |
          python settings.py
          python main.py
        env:
          YT_API: ${{ secrets.YT_API_ENV }}

# Gitのセットアップ
      - name: Setup Git
        run: |
          git config --local user.name "$secrets.GIT_USER_NAME"
          git config --local user.email "$secrets.GIT_USER_EMAIL"
        env:
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}

# ライブチャットデータを保存
      - name: Commit and Push
        run: |
          git config pull.rebase false
          git add .
          git commit -m "Request ready!" || echo "No changes to commit."
          git pull origin main
          git push origin main
