name: Tweet Data

# 一時的な実行方法
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
# おまじない
      - uses: actions/checkout@v2

# Pythonのセットアップ
      - name: Setup python
        uses: actions/setup-python@v2 
        with:
          python-version: "3.8"

# 必要なパッケージのインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

# チャットを取得するファイルを実行させる
      - name: Run tweet.py
        run: |
          python tweet.py
